# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV["RAILS_ENV"] ||= 'test'
ENV["GOVUK_APP_DOMAIN"] ||= 'test.gov.uk'
ENV["GOVUK_ASSET_ROOT"] ||= 'http://static.test.gov.uk'

require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'slimmer/rspec'
require 'webmock/rspec'

Dir[Rails.root.join("spec/support/**/*.rb")].each { |f| require f }

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
  config.raise_errors_for_deprecations!
  config.infer_spec_type_from_file_location!
end
